#pragma once

// Explicit prototypes for functions implemented in included module headers.
// This removes dependence on Arduino's .ino auto-prototype generator.
struct NagConfig;
struct NagContext;
struct S3xyCommandRequest;

static inline uint16_t nagModeCNextRawPure(uint16_t previousRaw, uint16_t &seed);
static inline void canTxBarrierInvalidatePure(CanTxBarrierState &state);
static inline void canTxBarrierMarkFreshPure(CanTxBarrierState &state, uint8_t busBit);
static inline bool canTxBarrierAllowsPure(const CanTxBarrierState &state, uint32_t expectedEpoch);
static inline bool manualDasStatePure(uint8_t state4);
static inline void canRxObserve(uint8_t bus, uint32_t frameNow);
static inline uint32_t canRxTotal();
static const char *s3xyStateName(uint8_t st);
static const char *s3xyActionCode(uint8_t action);
static const char *s3xyActionLabel(uint8_t action);
static uint8_t s3xyParseAction(const String &s);
static const char *s3xyLogTypeName(uint8_t t);
static void s3xyLogPush(uint8_t type, const char *detail, const uint8_t *data, size_t len, int16_t rssi, int8_t slot);
static void s3xyBytesToHex(const uint8_t *data, size_t len, char *out, size_t outLen);
static uint8_t s3xyHexNibble(char c);
static size_t s3xyHexToBytes(const char *src, uint8_t *out, size_t outMax);
static bool s3xyPeerIdEquals(const uint8_t *a, size_t aLen, const uint8_t *b, size_t bLen);
static void s3xySetAutoTrace(const String &detail);
static String s3xyJsonEscape(const char *src);
static bool s3xyAddressEquals(const char *a, const char *b);
static int s3xyFindSlotByAddress(const char *address);
static int s3xyFindSlotByPeerId(const uint8_t *peerId, size_t peerIdLen);
static bool s3xyHasEligibleSavedIdentity();
static bool s3xyIdentityCandidateCoolingDown(const char *address);
static void s3xyRejectIdentityCandidate(const char *address);
static int s3xyLocalBondCount();
static int s3xyFindFreeSlot();
static uint8_t s3xyRegisteredCount();
static uint8_t s3xyConnectedCount();
static bool s3xySlotIsUsed(int slot);
static void s3xyDefaultName(uint8_t slot, char *out, size_t outLen);
static void s3xyRegistrySaveSlot(uint8_t slot);
static void s3xyRegistryClearSlotRuntime(uint8_t slot, bool keepClient);
static void s3xyAutoLoadConfig();
static void s3xyAutoSetEnabled(bool enabled, bool persist);
static bool s3xyBluetoothMasterPersist(bool enabled);
static bool s3xyBluetoothMasterIsEnabled();
static bool s3xyRuntimeStopIsPending();
static bool s3xyMapperTaskIsRunning();
static bool s3xyWaitForRuntimeStopped(uint32_t timeoutMs);
static void s3xyRuntimeRearmAutoReconnect();
static void s3xyRequestRuntimeStop();
static void s3xyRuntimeShutdown();
static void s3xySetSlotError(uint8_t slot, const char *msg);
static void s3xyRunMappedAction(uint8_t slot, uint8_t action, const char *gesture);
static int s3xyFindToken2(const uint8_t *data, size_t len, uint8_t a, uint8_t b);
static int s3xyFindToken3(const uint8_t *data, size_t len, uint8_t a, uint8_t b, uint8_t c1, uint8_t c2);
static void s3xyNotifyCallbackForSlot(uint8_t slot, BLERemoteCharacteristic *chr, uint8_t *data, size_t len, bool isNotify);
static void s3xyNotifyCallbackSlot0(BLERemoteCharacteristic *chr, uint8_t *data, size_t len, bool isNotify);
static void s3xyNotifyCallbackSlot1(BLERemoteCharacteristic *chr, uint8_t *data, size_t len, bool isNotify);
static void s3xyNotifyCallbackSlot2(BLERemoteCharacteristic *chr, uint8_t *data, size_t len, bool isNotify);
static void (*s3xyNotifyCallbackForSlotIndex(uint8_t slot))(BLERemoteCharacteristic*, uint8_t*, size_t, bool);
static bool s3xyIsRegisteredAddress(const char *address);
static void s3xyDiscoveryAdd(const char *address, const char *name, int16_t rssi);
static bool s3xyMapperInit();
static void s3xyClearTarget();
static void s3xyResetLinkRuntime(uint8_t slot, uint8_t stateAfter);
static void s3xyDisconnectFailedLink(uint8_t slot, uint8_t stateAfter);
static bool s3xyScanTarget(const char *address, uint8_t seconds, int8_t slot);
static bool s3xyScanRegisteredWake(uint8_t seconds, int8_t &foundSlot);
static void s3xyDiscoveryScan();
static int s3xyProbeTargetIdentity();
static bool s3xyWriteHandshake(uint8_t slot);
static bool s3xyEnsureClient(uint8_t slot);
static bool s3xyConnectSlot(uint8_t slot);
static void s3xyBestEffortRemoteUnpair(uint8_t slot);
static void s3xyBestEffortRemoveBond(const char *address);
static bool s3xyPairAddress(const char *address);
static void s3xyForgetSlot(uint8_t slot);
static uint16_t s3xyRemoveAllLocalBonds();
static void s3xyResetAllBluetoothData();
static bool s3xyQueueCommand(uint8_t type, int8_t slot, const char *address);
static bool s3xyTakeCommand(S3xyCommandRequest &out);
static int s3xyFindDueAutoSlot(uint32_t now);
static void s3xyRunAutoAttempt(uint8_t triggerSlot);
static void s3xyMapperTask(void *arg);
static String s3xyStatsToJson();
static void csvEscapeField(const char *src, char *dst, size_t dstLen);
static void s3xyClearLog();
static inline uint32_t bootCaptureNowMs();
static void bootCaptureMarkOnce(volatile uint32_t *slot);
static void bootCaptureObservePartyFrame(uint16_t id, uint8_t dlc, const uint8_t *data);
static void bootCaptureObserveVhFrame(uint32_t id, uint8_t dlc);
static int8_t bootCaptureHardStart(uint8_t reason);
static void bootCaptureHardFinish(int8_t idx, bool success);
static const char* resetReasonName(esp_reset_reason_t r);
static uint32_t canTxEpochSnapshot();
static void canTxMarkFresh(uint8_t busBit);
static esp_err_t canTxTwaiTransmit(const twai_message_t *msg, uint32_t expectedEpoch);
static esp_err_t canTxTwaiClearQueue(uint32_t expectedEpoch);
static bool canTxMcpSend(const struct can_frame *msg, uint32_t expectedEpoch, MCP2515::ERROR &errOut,
                         McpTxResultReason *reasonOut = nullptr);
static void nagClampTorque(uint8_t& b2, uint8_t& b3);
static void nagCfgSetCommonDefaults(NagConfig& c);
static void nagCfgDefaultsModeA(NagConfig& c);
static void nagCfgDefaultsModeB(NagConfig& c);
static void nagCfgDefaultsModeC(NagConfig& c);
static void nagCfgDefaultsModeD(NagConfig& c);
static void nagCfgDefaultsModeE(NagConfig& c);
static void nagCfgDefaultsModeF(NagConfig& c);
static void nagCfgDefaultsModeH(NagConfig& c);
static void nagCfgClampAll(NagConfig& c);
static void nagCfgLoad();
static void nagCfgSave();
static bool nagDecideInjection(uint8_t dlc, uint8_t& out_b2, uint8_t& out_b3, bool& out_setHo);
static void nagExactEchoReset();
static void nagHumanRuntimeReset(bool reseed);
static NagHumanStepResultPure nagHumanRuntimeStep(uint32_t nowMs, uint16_t sourceRaw,
                                                  bool runAllowed, bool speedValid,
                                                  bool speedFresh, uint16_t speedRaw);
static NagHumanStatePure nagHumanRuntimeSnapshot();
static void nagHumanRuntimeApTransition(bool apActive, bool wasApActive);
static void nagUpdateApState(const uint8_t* data, uint8_t dlc);
static void nagUpdateSteering(const uint8_t* data, uint8_t dlc);
static void nagProcessMcpFrame(const struct can_frame& rxf);
static inline uint8_t readMuxID(const uint8_t *data);

enum T2CanBusId : uint8_t {
  T2CAN_BUS_PARTY = 0,
  T2CAN_BUS_VH = 1
};
static inline bool getBit(const uint8_t *data, int bit);
static inline void setBit(uint8_t *data, int bit, bool val);
static bool r79LabAnyOverrideSelected();
static bool r79LabPeriodValid(uint16_t ms);
static const char* r79LabGateReasonName(uint8_t reason);
static void r79LabObserve3fdMux1(const uint8_t *data, uint8_t dlc);
static bool r79LabApplySelectedBits(uint8_t *data);
static void r79LabRecordTxResult(bool ok, const twai_message_t &out, uint8_t txKind);
static void r79LabObserve7ff(uint8_t bus, uint8_t dlc, const uint8_t *data);
static inline uint8_t readVehicleGear(const uint8_t *data);
static inline int gearState(uint8_t gear);
static inline uint8_t readDASStatus(const uint8_t *data);
static inline uint8_t readDASState4(const uint8_t *data);
static inline uint8_t readDASAutoLaneChangeState(const uint8_t *data);
static bool autoBlinkerNOAGateOpen(uint32_t now, uint32_t* ageOut);
static bool autoBlinkerALCAllowsDirection(uint8_t reqDir, uint32_t now, uint8_t *alcOut);
static uint8_t autoBlinkerEligibleRequestDir(uint32_t now, uint8_t *alcOut);
static void ulcSnoozeSetResult(const char *text, uint8_t dir, bool accepted);
static bool ulcSnoozeRequestActive(uint32_t now);
static void ulcSnoozeFinishRequest();
static void handleS3xySingleAction();
static bool researchCaptureInit();
static const char *researchCaptureLabelSlotName(uint8_t slot);
static bool researchCaptureRequest(uint8_t labelSlot);
static bool researchCaptureSetMode(uint8_t mode);
static void researchCaptureObserveParty(uint16_t id, uint8_t dlc, const uint8_t *data);
static void researchCaptureObserveVh(uint16_t id, uint8_t dlc, const uint8_t *data);
static void researchCaptureObserveTxVh(uint16_t id, uint8_t dlc, const uint8_t *data, bool txOk);
static void researchCaptureObserveTxParty(uint16_t id, uint8_t dlc, const uint8_t *data, bool txOk);
static void researchCaptureTick(uint32_t now);
static void researchCaptureReset();
static String researchCaptureStatsToJson();
static bool httpRequireLab();
static void httpResearchCaptureStats();
static void httpResearchCaptureStart();
static void httpResearchCaptureLabels();
static void httpResearchCaptureReset();
static void httpResearchCaptureCsv();
static const char *pedalMapName(uint8_t v);
static const char *alcStateName(uint8_t v);
static const char* summonPriorityStateName(uint8_t state);
static const char* twaiStateName(int state);
static SummonRoutePure activeSummonRoute();
static uint8_t activeSummonRequiredTxFreshMask();
static bool summonPriorityFreshParkedLocked(uint32_t now);
static void recomputeSummonPriorityStateLocked(uint32_t now);
static void refreshSummonPriorityState();
static uint8_t getSummonPriorityState();
static bool twaiReadQueueStatus(twai_status_info_t *out);
static bool twaiNonSummonAdmissionOpen();
static bool manualDrivingGateOpen(uint32_t now);
static uint8_t ui334Checksum(const uint8_t *data);
static void requestPedalMapToggleFromButton();
static void handlePedalMap334OnCanB(const twai_message_t &src);
static void handlePedalMap334OnCanA(const struct can_frame &src);
static String pedalMapStatsJson();
static void httpPedalMapStats();
static esp_err_t canTxTwaiTransmitWithMask(const twai_message_t *msg, uint32_t expectedEpoch, uint8_t requiredFreshMask);
static esp_err_t canTxTwaiTransmitWithMaskWait(const twai_message_t *msg, uint32_t expectedEpoch, uint8_t requiredFreshMask, TickType_t waitTicks);
static esp_err_t canTxTwaiClearQueueWithMask(uint32_t expectedEpoch, uint8_t requiredFreshMask);
static uint8_t canTxFreshMaskSnapshot();
static esp_err_t twaiTransmitSummonPriority(const twai_message_t *msg, uint32_t txEpoch, uint8_t requiredFreshMask);
static inline uint32_t readBitsLE(const uint8_t *data, int startBit, int len);
static inline void writeBitsLE(uint8_t *data, int startBit, int len, uint32_t value);
static inline uint8_t sccm249Crc8(const uint8_t *data, uint8_t len);
static inline uint8_t leftStalkChecksum(const uint8_t frame[4], uint8_t counter);
static inline uint8_t dirToTurn(uint8_t dir);
static void handle249OnCanB(const uint8_t *data, uint8_t dlc);
static void handle249OnCanA(const uint8_t *data, uint8_t dlc);
static void handle3C2OnCanA(const struct can_frame &incoming);
static void handle102LaneChangeCancel(const uint8_t *data, uint8_t dlc);
static void sendStalkFrameCanB(uint8_t turn, uint32_t txEpoch);
static void sendStalkFrameCanA(uint8_t turn, uint32_t txEpoch);
static void evaluateAutoBlinker();
static void blinkATxTick();
static inline bool isDASActive(uint8_t status);
static bool nagApInjectionGateOpen();
static void nagApGateSnapshot(bool &validOut, bool &activeOut);
static inline bool summonGateGraceActiveLocked(uint32_t now);
static inline void expireSummonGateGraceLocked(uint32_t now);
static inline void recoverSummonGateGraceLocked();
static inline bool summonInjectionGateOpen();
static void handle280(const uint8_t *data);
static void handle390(const uint8_t *data);
static void handle921(const uint8_t *data, uint8_t dlc);
static void handle1016(const uint8_t *data, uint8_t dlc);
static bool lab3f8AutosteerGateOpen(uint32_t now);
static bool lab3f8AnyOverrideSelected();
static void injectDriverAssistControl(const twai_message_t &src);
static void injectSummon(const twai_message_t &src);
static void doInjectTlsscRestore(const twai_message_t &src);
static uint8_t r79LabGateReason(uint32_t now);
static bool r79LabTransmitShadow(const uint8_t *stock, uint32_t now, uint8_t gateReason, uint8_t txKind, uint32_t txEpoch, uint8_t requiredFreshMask);
static void r79LabPeriodicTick();
static void injectTLSSC(const twai_message_t &src);
static void featureCfgLoad();
static void featureCfgSave();
static void summonCfgLoad();
static void summonCfgSave();
static void lab3f8CfgLoad();
static void lab3f8CfgSave();
static void r79LabCfgLoad();
static void r79LabCfgSave();
static String nagCfgToJson();
static String nagStatsToJson();
static String summonStatsToJson();
static String blinkAStatsToJson();
static String dasTelemetryStatsToJson();
static String lab3f8StatsToJson();
static const char* r79LabTxKindName(uint8_t kind);
static String r79LabStatsToJson();
static String systemStatsToJson();
static const char* bootCaptureHardReasonName(uint8_t reason);
static void bootCaptureAppendEvent(String &out, const char *event, uint32_t t, const String &detail);
static String bootCaptureToCsv();
static void httpBootCaptureCsv();
static void httpS3xyStats();
static int s3xyHttpSlotArg();
static bool httpS3xyRequireBluetooth();
static void httpS3xyBluetoothEnable();
static void httpS3xyBluetoothDisable();
static void httpS3xyResetAllBluetooth();
static void httpS3xyScan();
static void httpS3xyPair();
static void httpS3xyDeviceConnect();
static void httpS3xyDeviceDisconnect();
static void httpS3xyDeviceForget();
static void httpS3xyDeviceHandshake();
static void httpS3xyDeviceRename();
static void httpS3xyDeviceAction();
static void httpS3xyDeviceAuto();
static void httpS3xyAutoEnable();
static void httpS3xyAutoDisable();
static void httpS3xyClear();
static void httpS3xyLogCsv();
static void httpOtaUpload();
static void httpOtaFinish();
static void httpSystemStats();
static void httpCanHardReinit();
static void httpRebootT2Can();
static void httpRoot();
static void httpNagConfig();
static void httpNagStats();
static void httpNagSetMode();
static void httpNagUpdate();
static void httpNagReset();
static void httpSummonStats();
static void httpSummonTlsscEnable();
static void httpSummonTlsscDisable();
static void httpDasTelemetryStats();
static void httpR79LabStats();
static void httpR79LabUpdate();
static void httpR79LabStock();
static void httpLab3f8Stats();
static void httpLab3f8Update();
static void httpLab3f8Stock();
static void httpBlinkAStats();
static void httpBlinkAEnable();
static void httpBlinkADisable();
static void httpBlinkADelay();
static void resetRuntimeStats();
static void httpResetRuntimeStats();
static void webTask(void *arg);
static void invalidateCanTxStateForCanARecovery();
static void invalidateCanTxStateForCanBRecovery();
static void invalidateCanTxStateForFullRecovery();
static bool mcpInitChecked();
static bool mcpReinit();
static void canTaskMcp(void* arg);
static void canTaskTwai(void* arg);
static inline bool recoveryFresh(uint32_t now, uint32_t ts, uint32_t timeoutMs);
static void requestCanSubsystemRestart(uint8_t reason, uint8_t diagReason);
static bool recoveryMcpColdInit();
static bool recoveryTwaiInstallFresh();
static bool recoveryTwaiFullReinit();
static void recoveryStopCanTasks();
static bool recoveryStartCanTasks();
static bool recoveryHardReinitialize(uint8_t reason, uint8_t diagReason);
static void canSupervisorTask(void* arg);
