// Browser regression fixture only. Derived from tools/dashboard_demo/mock.js.
// Loaded through Playwright addInitScript; never embedded in firmware HTML.
/* Preview-only API simulator. Every value is synthetic; no vehicle, Wi-Fi, BLE or OTA hardware is accessed. */
(()=>{
  'use strict';
  const VERSION='3.26.3', query=new URLSearchParams(location.search), clone=x=>JSON.parse(JSON.stringify(x));
  const routes=new Map(), methods=new Map();
  let state, apSince=Date.now();
  // Separate query presets share no saved state. Reloading a preset preserves its simulated settings.
  const storageKey='t2-dashboard-demo:'+VERSION+':'+['previewModel','previewTopology','previewTurn','previewAp','previewSetup','allFeatures'].map(k=>query.get(k)||'').join(':');
  function persist(){try{window.localStorage?.setItem(storageKey,JSON.stringify({version:VERSION,state}))}catch(e){/* Storage may be disabled in private previews. */}}
  const profileNames=['Setup','Model Y L','Model Y Juniper','Model Y Legacy','Model 3 Highland','Model 3 Legacy'];
  const bool=v=>['1','true','on'].includes(String(v));
  function fail(status,message){throw Object.assign(new Error(message),{status})}
  function num(p,k,min,max,integer=true){const raw=p.get(k),n=Number(raw);if(raw===null||raw.trim()===''||!Number.isFinite(n)||(integer&&!Number.isInteger(n))||n<min||n>max)fail(400,'Invalid '+k);return n}
  function patch(target,p,spec){const next={};for(const [k,range] of Object.entries(spec)){if(!p.has(k))continue;next[k]=range==='bool'?(['0','1','true','false','on','off'].includes(p.get(k))?bool(p.get(k)):fail(400,'Invalid '+k)):num(p,k,...range)}Object.assign(target,next);return target}
  function defaults(){
    const m=Number(query.get('previewModel')),model=[1,2,3,4,5].includes(m)?m:1;
    const topology=model===1?1:Number(query.get('previewTopology'))===3?3:2;
    const turn=topology===3?0:model===4&&Number(query.get('previewTurn'))!==1?2:1;
    return {model,topology,turn,ap:['OFF','AUTOSTEER','NOA'].includes(query.get('previewAp'))?query.get('previewAp'):'NOA',scenario:'driving',allFeatures:query.get('allFeatures')==='1',setupMode:query.get('previewSetup')==='1',started:Date.now(),reboots:0,
      wifi:{ssid:'T2CAN-DEMO',ip:'192.168.4.1',passwordIsDefault:false},
      features:{lab:true,s3xy:true,doorCancel:false,banned:false,tlsscRestore:false,apDriveProfile:false,apDriveProfileRegenRaw:10},
      nag:{enabled:true,ignoreApState:false,method:topology===2?1:0,tsl9Sequence:0,tsl9IntervalMode:0,tsl9InputMode:0,tsl9Window:0,tsl9RightPeriodicEnabled:false,tsl9RightPeriodicIntervalSeconds:30,tsl9LegacyRoute:0,torqueRightScrollEnabled:false,torqueRightScrollIntervalSeconds:30,torqueRightScrollPattern:1,pauseAtZeroSpeed:false,mode:7,humanVariant:4,modeHStopBehavior:0,hoRatePct:50,burstMs:300,pauseMs:2000,targetId:0x488,apStateId:0x399,steeringId:0x370,torque:[{b2:7,b3:239},{b2:8,b3:21}]},
      human:{peakMinNm:1.8,peakMaxNm:2.6,waitMinMs:900,waitMaxMs:3000,refractoryMinMs:500,refractoryMaxMs:1500,carrierMinNm:.1,carrierMaxNm:.6,hoPolicy:2,ho1ThresholdNm:.4,ho2ThresholdNm:2,visualRescueEnabled:true,visualRescueDelayMs:500},
      driverMonitoring:{enabled:true},isa:{enabled:false},
      blink:{enabled:true,delayMs:300,noaStabilizationSeconds:10,cancelPauseSeconds:20,txMode:model===1?0:1,txRequests:12,txBlocked:0,txOk:12,txFail:0,txActiveSource:'NONE',txLastSource:'DEMO AUTO',txLastResult:'DEMO OK',txLastDirection:1},
      summon:{tlssc:false,tlsscHighwayGateEnabled:true,tlsscBlockInNoa:true},
      r79:{mode:1,mode1TxWaitMode:1,mode1ReinjectEnabled:true,mode1DelayMs:150,mode2ReinjectEnabled:false,mode2DelayMs:150,bit18Mode:0,hw3Enabled:false,txOk:42118,txFail:0},
      r79Ap:{enabled:false,mode:0,delaySeconds:2,allowManualDriving:false},
      ulc:{alcMode:0,ulcOffHighwayMode:255,ulcBlindMode:255,stalkConfirmEnabled:false,stalkConfirmTimingMode:0,autoLaneChangeEnabled:false,autoLaneChangeTargetBus:3,txOk:0,txFail:0,gateBlocked:0},
      country:{countryMode:0,mapMode:0,countryTxOk:0,countryTxFail:0},vision:{requestDisabled:false,bus:0,txOk:0,txFail:0},heartbeat:{enabled:false,selectedValue:2,appliedCount:0,txFail:0,blocked:0},
      driverWindow:{requests:0,completed:0,blocked:0,txOk:0,txFail:0,lastResult:'WAITING'},
      pedal:{targetRaw:255,originRaw:1,txOk:0,txFail:0,immediateTxOk:0,immediateTxFail:0,followTxOk:0,followTxFail:0},
      research:{captureMode:'SNAPSHOT',preWindowMs:2000,postWindowMs:5000,labels:{A:'DEMO baseline',B:'DEMO AP active',C:'DEMO left lane',D:'DEMO right lane'},samples:0,completedSegments:0,requests:0,lastSlot:'NONE',lastLabel:'',history:[]},
      monitor:{samples:0,segments:0,requests:0,history:[]},
      s3xy:{bluetoothEnabled:true,autoEnabled:true,diagnosticsEnabled:true,devices:[device(1,'DEMO Driver Button'),device(2,'DEMO Passenger Button')],scanResults:[],scanState:'IDLE',scanError:'',ulcTxOk:0,ulcTxFail:0,ulcAccepted:0,ulcBlocked:0,ulcLastDir:0},
      system:{canHardReinit:0,canHardReinitFail:0,canLastHardReason:'NONE',canLastHardDiagReasonName:'NONE',mcpTxOk:89687,mcpTxFail:0},ota:{uploads:0,message:'Demo only · no firmware is flashed'}
    };
  }
  function device(id,name,address){return {id,name,address:address||'DE:00:00:00:00:0'+id,connected:true,state:'READY',secure:true,subscribed:true,autoConnect:true,rssi:-45-id*5,notifyCount:id===1?27:8,singleAction:'left_blinker',doubleAction:'right_blinker',longAction:'noa_cancel',singleCount:10,doubleCount:8,longCount:9,addressTypeKnown:true,addressType:1,peerIdLen:16,idHex:'DEMO-'+id,identityPersistVerified:true,handshakeAckCount:1,lastNotify:'DEMO SINGLE',error:'NONE',autoReconnects:0,autoAttempts:1,autoFailures:0,lastAutoPath:'DEMO',lastDiscoverMs:90,lastConnectMs:180,lastReadyMs:350};}
  function expose(){window.__t2PreviewState=state;window.__t2DemoState=state;}
  function reset(){state=defaults();apSince=Date.now();expose();persist();return state;}
  state=defaults();
  try{const saved=JSON.parse(window.localStorage?.getItem(storageKey)||'null');if(saved?.version===VERSION&&saved.state?.nag&&saved.state?.s3xy){state=saved.state}}catch(e){/* Corrupt or unavailable preview storage starts fresh. */}
  expose();window.__t2DemoUnhandled=[];window.__t2CopyRequests=[];
  window.__t2DemoReset=reset;
  window.__t2PreviewSetAp=next=>{if(!['OFF','AUTOSTEER','NOA'].includes(next))return false;if(state.ap!==next)apSince=Date.now();state.ap=next;persist();return true};
  window.__t2DemoSetAllFeatures=v=>{state.allFeatures=!!v;persist();return profile()};
  window.__t2DemoSetScenario=next=>{if(!['driving','parked','summon','offline'].includes(next))return false;state.scenario=next;state.ap=next==='driving'?'NOA':'OFF';apSince=Date.now();if(next==='parked')state.pedal.targetRaw=255;persist();return true};
  const online=()=>state.scenario!=='offline';
  const engaged=()=>online()&&state.ap!=='OFF'&&state.scenario==='driving'&&!state.setupMode;
  const noa=()=>engaged()&&state.ap==='NOA';
  const das=()=>state.ap==='NOA'?5:state.ap==='AUTOSTEER'?3:0;
  const lab=()=>{if(!state.features.lab)fail(409,'DEMO LAB is disabled')};
  function profile(){const a=state.allFeatures,t=state.topology;return {demo:true,demoAllFeatures:a,setupMode:state.setupMode,migrationNotice:false,profile:state.model,profileName:profileNames[state.model],topology:t,turn:state.turn,topologyName:{1:'Party + VH',2:'Body + Chassis',3:'Party + Chassis'}[t],canA:t===2?'BODY':'PARTY',canB:t===1?'VH':'CHASSIS',nagSupported:true,nagTorqueSupported:a||t!==2,nagTsl9Supported:a||t!==3,advancedEapSupported:a||t!==3,euUnlockSupported:true,pedalMapSupported:a||t!==3,apDriveProfileSupported:a||t!==3,turnSignalSupported:a||state.turn!==0,driverWindowSupported:a||state.model===1,dmsNagSupported:true};}
  function features(){const p=profile();return {...state.features,demo:true,demoAllFeatures:state.allFeatures,bannedSupported:state.allFeatures||state.model!==1,tlsscRestoreSupported:state.allFeatures||state.model!==1,tlsscRestoreSupported:state.allFeatures||state.model!==1,pedalMapSupported:p.pedalMapSupported,apDriveProfileSupported:p.apDriveProfileSupported};}
  function nagStats(){const run=state.nag.enabled&&(engaged()||(state.nag.ignoreApState&&online()&&state.scenario==='driving')),p=profile();return {demo:true,torque:.03,ho:0,handsOnState:0,injNm:run?-.22:0,injHo:run?1:0,rx:online()?90222:0,txOk:run?89687:0,txFail:0,lastTxAgeMs:run?15:999999,maxTxGapMs:40,apActive:engaged(),canAState:online()?1:0,dasStateValid:online(),dasState:das(),dasAgeMs:online()?15:999999,sessionTxOk:run?18697:0,lastSkip:!online()?'STALE':run?'NONE':'AP_INACTIVE',lastSkipAgeMs:run?999999:15,vehicleSpeedValid:online(),vehicleSpeedKph:state.scenario==='driving'?71.2:state.scenario==='summon'?2.1:0,vehicleSpeedFresh:online(),stoppedGate:state.scenario==='parked',stopCarrierActive:state.scenario==='parked'&&state.nag.modeHStopBehavior===1,humanPhase:run?'PEAK':'WAIT',humanMotion:state.scenario==='parked'?'STOPPED':'DRIVING',humanEventType:'DEMO HUMAN',humanEventCount:31,humanDirection:-1,humanOutputNm:run?-.22:0,humanCarrier:false,humanSessionAgeMs:18500,tsl9Rx:p.nagTsl9Supported?1240:0,tsl9TxOk:state.nag.method===1&&run?1240:0,tsl9TxFail:0,tsl9Modified:state.nag.method===1&&run?1240:0,lastTxBlock:run?'NONE':'AP_INACTIVE'};}
  function dms(){return {...state.driverMonitoring,demo:true,supported:true,active:state.driverMonitoring.enabled&&engaged()};}
  function isa(){return {...state.isa,demo:true,supported:profile().nagTsl9Supported,active:state.isa.enabled&&engaged()&&profile().nagTsl9Supported,route:state.model===1?'PARTY_0x399':'CHASSIS_0x399',modified:0,txOk:0,txFail:0};}
  function human(){const n=nagStats();return {...state.human,demo:true,stopBehavior:state.nag.modeHStopBehavior,stopCarrierActive:n.stopCarrierActive,stopCarrierTxOk:0,phase:n.humanPhase,eventType:n.humanEventType,outputNm:n.humanOutputNm,activeEventPeakNm:2.1,carrier:false,visualRescuePending:false,visualRescueCount:0};}
  function blink(){return {...state.blink,demo:true,dasState:das(),displayState:das(),dasStateValid:online(),displayStateValid:online(),canReinitializing:false,noaRawActive:noa(),noaActive:noa(),noaStabilized:noa(),noaSessionStateName:noa()?'READY':'INACTIVE',noaStabilizationRemainingMs:0,noaExitRemainingMs:0,cancelPaused:false,cancelPauseRemainingMs:0,autoArmed:false,autoWaitingEligibility:false,autoRemainMs:0,autoRetryInMs:0,autoRetryCount:0,behaviorType:'DEMO',alcState:engaged()?8:0,alcValid:online(),alcDirectionAllowed:noa(),pendingAlcAllowed:noa(),visualFresh:online(),visualAgeMs:online()?22:999999,activeTurn:0,seen249:online(),cksumSelfTest:true,realRaw:'DEMO 00 00 00 00 00 00 00 00',visualDebugRx:online()?1400:0};}
  function summon(){const s=state.scenario==='summon',p=profile();return {...state.summon,demo:true,summon:s,sessionActive:s,canState:online()?1:0,canStateName:online()?'RUNNING':'STOPPED',priorityStateName:s?'ACTIVE':'NORMAL',summonRouteValid:online(),gearBusName:p.canB,sprBusName:p.canB,transportBusName:p.canB,confirmedGearStateName:state.scenario==='parked'?'PARK':'DRIVE',confirmedGearSourceName:'DEMO',confirmedGearAgeMs:18,confirmedGearTransitions:1,acaFresh:online(),aca:s,acaAgeMs:18,sprFresh:online(),sprRaw:s?1:0,sprAgeMs:22,remoteStartupEvidence:s,manualLatchActive:false,loadSheddingActive:s,txQueueNow:0,txQueueMax:4,nonSummonShed:0,parkSoftShed:0,readyShed:0,activeShed:s?12:0,r79LastRetryAgeMs:999999,rx280:450,rx390:700,rx921:1200,rx1016:900,roadContextValid:online(),roadContextFresh:online(),roadContextAgeMs:25,gpsRoadMatch:true,roadClass:2,controlledAccess:true,leftOffRamp:false,rightOffRamp:false,tlsscHighwayConfirmed:online()&&state.scenario==='driving',tlsscHighwayBlocked:state.scenario!=='driving',tlsscInjectedActive:state.summon.tlssc&&engaged()&&!(state.summon.tlsscBlockInNoa&&noa()),tlsscClearPending:false,tlsscClearTxOk:0,tlsscClearTxFail:0};}
  function apControl(){
    const c=state.r79Ap,apActive=engaged();
    const wait=c.enabled&&c.mode===1&&apActive?Math.max(0,c.delaySeconds*1000-(Date.now()-apSince)):0;
    const reason=!c.enabled?'BYPASS':!online()?'AP_UNKNOWN':!apActive?'NON_AP':c.mode===0?'AP_BLOCKED':wait?'AP_WAIT':'AP_READY';
    return {...c,demo:true,apActive,gateAllowed:['BYPASS','NON_AP','AP_READY'].includes(reason),remainingMs:wait,gateReason:reason};
  }
  function r79(){
    const c=apControl(),s=state.scenario==='summon';
    const legacyAllowed=s||engaged()||state.scenario==='parked'||state.r79Ap.allowManualDriving;
    const txState=!online()?'CAN OFFLINE':!legacyAllowed?'SUSPENDED':!c.gateAllowed?({'AP_BLOCKED':'AP BLOCKED','AP_WAIT':'AP WAIT'}[c.gateReason]||'AP UNKNOWN'):'ACTIVE';
    const active=txState==='ACTIVE';
    const hw3Supported=state.allFeatures||([3,5].includes(state.model)&&[2,3].includes(state.topology));
    const hw3Active=state.r79.hw3Enabled&&hw3Supported,stockBit47=state.r79.stockBit47===0?0:1;
    return {...state.r79,demo:true,modeName:state.r79.mode===1?'Mode 1 · SmartSummonOnly':'Mode 2 · Full R79',fixedPolicy:true,txState,txReason:engaged()?'AUTOPILOT':s?'SUMMON':!legacyAllowed?'MANUAL D':'DEFAULT',gearName:state.scenario==='parked'?'P':'D',dasStateValid:online(),dasState:das(),lastTxValid:active,lastTxAgeMs:active?12:999999,apWaitRemainingMs:c.remainingMs,apGateReason:c.gateReason,transport:'DEMO CAN B · '+profile().canB,periodic:'20 Hz · synthetic',smartMode:1,bit18ModeName:state.r79.bit18Mode?'FORCE_0':'STOCK',runtimeState:txState,stockTemplateValid:online(),stockMux1Rx:90222,fastAttempts:42118,fastTxOk:42118,fastTxFail:0,periodicTxOk:48069,periodicTxFail:0,quietArm:12,quietFire:12,quietGuardSkip:0,dmsNagActive:dms().active,stockBit43Valid:online(),stockBit43:1,effectiveBit43Valid:online(),effectiveBit43:dms().active?0:1,hw3Supported,hw3Active,bit47ModeName:hw3Active?'STOCK':'FORCE_1',stockBit47Valid:online(),stockBit47,bit47Valid:!hw3Active||online(),bit47:hw3Active?stockBit47:1};}
  function ulc(){const c=state.ulc,p=profile();return {...c,demo:true,stalkConfirmSupported:p.advancedEapSupported,stalkConfirmGateOpen:state.features.lab&&c.stalkConfirmEnabled&&online()&&(engaged()||c.stalkConfirmTimingMode===1),policyGateOpen:state.features.lab&&engaged(),stockStalkConfirmValid:online(),stockStalkConfirm:1,stalkConfirmCanAName:p.canA,stalkConfirmCanBName:p.canB,stalkConfirmTxOk:0,stalkConfirmTxFail:0,stalkConfirmTxBOk:0,stalkConfirmTxBFail:0,stalkConfirmLastTxValid:false,driverAssistBit1B:online()?1:-1,driverAssistHzB:20,driverAssistAgeBMs:25,driverAssistRxB:1240,driverAssistRawB:'DEMO 00 02 00 00 00 00 00 00',autoLaneChangeGateOpen:state.features.lab&&engaged()&&c.autoLaneChangeEnabled,autoLaneChangeStockAValid:online(),autoLaneChangeStockBValid:online(),autoLaneChangeStockARaw:0,autoLaneChangeStockBRaw:0,autoLaneChangeStockAAgeMs:21,autoLaneChangeStockBAgeMs:22,autoLaneChangeRxA:800,autoLaneChangeRxB:1200,stockUlcBlindSpot:0,rxAgeMs:20,autoLaneChangeLastTxValid:false};}
  function country(){const p=profile();return {...state.country,demo:true,countrySupported:true,countryGateOpen:r79().txState==='ACTIVE'&&(state.country.countryMode!==0||state.country.mapMode!==0),gateAllowed:r79().txState==='ACTIVE',countryRx238:1200,countryRx7ffA:200,countryRx7ffB:220,countryBlocked:0,countryLastValid:false,countryCanAName:p.canA,countryCanBName:p.canB,r79StockValid:online(),r79StockBit19:1,r79StockBit47:1,r79StockAgeMs:22,r79StockRx:1240,r79StockRaw:'DEMO 00 00 08 00 00 80 00 00'};}
  function vision(){const p=profile(),body=state.allFeatures||(state.model!==1&&state.topology===2),route=state.vision.bus===0||body,gate=state.features.lab&&state.vision.requestDisabled&&engaged()&&route;return {...state.vision,demo:true,supported:true,bodySupported:body,busSupported:route,busSelectorVisible:state.allFeatures||state.model!==1,labEnabled:state.features.lab,apActive:engaged(),apFresh:online(),stockValid:online(),stockBit:1,rxAgeMs:online()?24:999999,rxCount:1240,gateOpen:gate,state:!state.vision.requestDisabled?'OFF':!route?'UNSUPPORTED':!online()?'WAIT_STOCK':engaged()?'READY':'WAIT_AP'};}
  function heartbeat(){const c=state.heartbeat,supported=state.allFeatures||state.model===1,gate=c.enabled&&state.features.lab&&supported&&online()&&state.scenario==='summon';return {...c,demo:true,supported,labEnabled:state.features.lab,stockValid:online(),stockValue:1,stockAgeMs:22,gateOpen:gate,state:!c.enabled?'OFF':!online()?'WAIT_STOCK':gate?'ACTIVE':'BLOCKED',lastAppliedValid:gate,lastAppliedValue:gate?c.selectedValue:1};}
  function driverWindow(){const available=online()&&state.features.lab&&profile().driverWindowSupported&&state.scenario==='parked';return {...state.driverWindow,demo:true,available,pending:false,availability:available?'DEMO PARK · READY':!profile().driverWindowSupported?'UNSUPPORTED':!online()?'CAN OFFLINE':!state.features.lab?'LAB OFF':'PARK REQUIRED',stockAgeMs:online()?22:999999,stockRaw:'DEMO 00 00 00 00 00 00 00 00',lastTxRaw:state.driverWindow.completed?'DEMO 00 00 00 00 00 00 08 00':'—'};}
  function pedal(){const c=state.pedal,name=n=>({0:'CHILL',1:'SPORT',2:'PERFORMANCE',255:'STOCK'}[n]||'STOCK');return {...c,demo:true,supported:profile().pedalMapSupported,valid:online(),stockRaw:1,stockName:'SPORT',overrideActive:c.targetRaw!==255,targetName:name(c.targetRaw),ageMs:online()?24:999999,blocked:0};}
  function capture(){const c=state.research,p=profile();return {...c,demo:true,state:c.completedSegments>=8?'FULL':'READY',capturing:false,capacity:8192,segment:c.completedSegments,maxSegments:8,knownIds:42,preSnapshotsReady:10,preSnapshotSlots:10,lastPreSnapshotsCopied:10,lastTriggerRows:42,lastPostSnapshotsCopied:4,postSnapshotCount:4,usingPsram:true,memoryBytes:1048576,psramFreeBytes:5242880,psramTotalBytes:8388608,rawAutoAlcSupported:state.allFeatures,rawPreReady:online(),rawManualPreReady:online(),rawPreMs:5000,rawPreCoverageMs:5000,rawRingUsagePct:12.5,rawArchiveUsagePct:c.completedSegments*5,rawEvicted:0,autoLastFrom:255,autoLastTo:255,autoLastTriggerAgeMs:999999,lane239Valid:online(),virtualLaneWidth:3.55,laneViewRange:120,virtualLaneC0:.02,virtualLaneC1:.001,virtualLaneC2:0,canAName:p.canA,canBName:p.canB,remainingMs:0,ignored:0,dropped:0};}
  function monitor(){const c=state.monitor,p=profile(),out={...c,demo:true,supported:true,state:c.segments>=12?'FULL':'READY',capturing:false,maxSegments:12,capacity:1024,preCoverageMs:2000,interactionRaw:0,interactionName:'HANDS ON',previousInteractionRaw:1,previousInteractionName:'HANDS OFF',interactionChangeAgeMs:5000,canAName:p.canA,canBName:p.canB,epasHandsOnRaw:0,epasTorqueNm:.03,dasHandsOnRaw:0,remainingMs:0,usingPsram:true,ignored:0,dropped:0};for(const id of ['389','5d9','247','399','370'])Object.assign(out,{['bus'+id]:id==='370'?0:1,['age'+id+'Ms']:20,['count'+id]:1240,['raw'+id]:'DEMO 00 00 00 00 00 00 00 00'});return out;}
  function s3xy(){const c=state.s3xy;return {...c,demo:true,bleInitialized:c.bluetoothEnabled,pairedCount:c.devices.length,connectedCount:c.devices.filter(d=>d.connected&&c.bluetoothEnabled).length,maxDevices:3,bleStack:'DEMO NimBLE',arduinoCore:'DEMO 3.x',bootLocalBondCount:c.devices.length,localBondCount:c.devices.length,scanSupported:true,scanning:false,bondRepairArmed:false,autoTrace:'Synthetic preview state',ulcResult:'DEMO IDLE'};}
  function system(){return {...state.system,demo:true,fwVersion:VERSION,uptimeS:Math.floor((Date.now()-state.started)/1000),freeHeap:241664,minFreeHeap:210944,largestHeapBlock:184320,stackCanA:4096,stackCanB:4096,stackCanSup:3072,stackWeb:7168,stackS3xy:5120,twaiTxQueueNow:0,twaiTxQueueMax:4,twaiRxQueueNow:0,twaiRxQueueMax:6,s3xyLogCapacity:1024,mcpState:0,mcpErrorFlags:0,mcpErrorFlagsAgeMs:20,mcpTxFailConsecutive:0,mcpBusOffSnapshotValid:false,twaiStateName:online()?'RUNNING':'STOPPED',twaiLastEventReasonName:'DEMO NONE',twaiLastEventAgeMs:999999,twaiBusOffSnapshotValid:false,twaiBusErrSessionAvg:0,twaiBusErrSessionMin:0,twaiArbLostSessionAvg:0,twaiArbLostSessionMin:0,twaiBusOffSessionAvg:0,twaiBusOffSessionMin:0,canHeartbeatLastCauseName:'DEMO NONE',canHeartbeatLastAgeAMs:0,canHeartbeatLastAgeBMs:0,canHeartbeatTimeoutA:0,canHeartbeatTimeoutB:0,canHeartbeatTimeoutBoth:0,canABusOffRecord:{busOffRecordBoot:'NONE'},canBBusOffRecord:{busOffRecordBoot:'NONE'},demoReboots:state.reboots};}
  function alc(){return {demo:true,alcValid:online(),alcRaw:engaged()?8:0,alcAgeMs:10,lane239Valid:online(),lane239AgeMs:14,leftLaneExists:1,leftLineUsageRaw:2,leftForkRaw:0,rightLaneExists:1,rightLineUsageRaw:2,rightForkRaw:0};}
  function snapshot(p){const slow=()=>({blink:blink(),summon:summon(),s3xy:s3xy(),r79:r79(),lab3f8:ulc()});switch(p.get('groups')){case 'home-fast':return {fast:{nag:nagStats(),blink:blink(),summon:summon(),r79:r79(),cantraffic:{mcpTrafficSeen:true,mcpTrafficOnline:online(),mcpTrafficAgeMs:online()?18:15000,twaiTrafficSeen:true,twaiTrafficOnline:online(),twaiTrafficAgeMs:online()?22:15000}},...(p.has('slow')?{slow:slow()}:{})};case 'home-slow':return slow();case 'settings-lite':return {system:system(),...slow()};case 'lab-lite':return {r79:r79(),alc:alc(),dmsNag:dms()};case 'system':return {system:system()};default:fail(400,'Unknown snapshot group')};}
  function route(path,method,handler){routes.set(path,handler);methods.set(path,method);}
  const readers={'/api/profile/status':profile,'/api/features/status':features,'/api/wifi/status':()=>({...state.wifi,demo:true,ok:true}),'/api/nag/config':()=>state.nag,'/api/nag/stats':nagStats,'/api/nag/h-profile/stats':human,'/api/blinkA/stats':blink,'/api/summon/stats':summon,'/api/r79/stats':r79,'/api/r79/ap-control/stats':apControl,'/api/ulc/stats':ulc,'/api/lab/auto-lane-change/stats':ulc,'/api/country/stats':country,'/api/lab/country/stats':country,'/api/vision-control/stats':vision,'/api/lab/vision-control/stats':vision,'/api/lab/summon-heartbeat/stats':heartbeat,'/api/lab/driver-window/stats':driverWindow,'/api/pedalmap/stats':pedal,'/api/researchcapture/stats':capture,'/api/drivermonitor/stats':monitor,'/api/s3xy/stats':s3xy,'/api/system/stats':system,'/api/das/stats':()=>({...alc(),dasState:das(),dasStateValid:online()}),'/api/snapshot':snapshot};
  for(const [path,handler] of Object.entries(readers))route(path,'GET',handler);
  route('/api/nag/update','POST',p=>{const spec={enabled:'bool',ignoreApState:'bool',pauseAtZeroSpeed:'bool',method:[0,1],tsl9Sequence:[0,1],tsl9IntervalMode:[0,1],tsl9InputMode:[0,1],tsl9Window:[0,1],tsl9RightPeriodicEnabled:'bool',tsl9RightPeriodicIntervalSeconds:[1,600],tsl9LegacyRoute:[0,1],torqueRightScrollEnabled:'bool',torqueRightScrollIntervalSeconds:[1,600],torqueRightScrollPattern:[0,1],modeHStopBehavior:[0,1],targetId:[0,0x7ff],apStateId:[0,0x7ff],steeringId:[0,0x7ff],hoRatePct:[0,100],burstMs:[1,60000],pauseMs:[0,60000]};const next=clone(state.nag);patch(next,p,spec);if(next.method===0&&!profile().nagTorqueSupported||next.method===1&&!profile().nagTsl9Supported)fail(409,'Nag method unsupported for topology');if(p.has('count')){const n=num(p,'count',1,32);next.torque=[];for(let i=0;i<n;i++)next.torque.push({b2:num(p,'b2_'+i,0,255),b3:num(p,'b3_'+i,0,255)})}state.nag=next;return next});
  route('/api/nag/mode','POST',p=>{const m=num(p,'m',0,7);if(![0,1,3,7].includes(m))fail(400,'Invalid mode');state.nag.mode=m;return state.nag});
  route('/api/nag/h-variant','POST',p=>{state.nag.humanVariant=num(p,p.has('v')?'v':'variant',1,4);return state.nag});
  route('/api/nag/reset','POST',()=>{state.nag=defaults().nag;return state.nag});
  route('/api/nag/h-profile/reset','POST',()=>{state.human=defaults().human;return human()});
  route('/api/nag/h-profile/update','POST',p=>{const next=clone(state.human);patch(next,p,{peakMinNm:[1,3,false],peakMaxNm:[1,3,false],waitMinMs:[300,5000],waitMaxMs:[300,5000],refractoryMinMs:[300,2500],refractoryMaxMs:[300,2500],carrierMinNm:[.1,.8,false],carrierMaxNm:[.1,.8,false],hoPolicy:[0,2],ho1ThresholdNm:[.1,3,false],ho2ThresholdNm:[.1,3,false],visualRescueEnabled:'bool',visualRescueDelayMs:[0,2000]});for(const pair of [['peakMinNm','peakMaxNm'],['waitMinMs','waitMaxMs'],['refractoryMinMs','refractoryMaxMs'],['carrierMinNm','carrierMaxNm'],['ho1ThresholdNm','ho2ThresholdNm']])if(next[pair[0]]>next[pair[1]])fail(400,'Minimum exceeds maximum');state.human=next;return human()});
  for(const [path,key,reader] of [['/api/driver-monitoring/config','driverMonitoring',dms],['/api/isa-suppression/config','isa',isa]])route(path,'GET,POST',(p,method)=>{if(method==='POST'){const next=clone(state[key]);patch(next,p,{enabled:'bool'});if(!p.has('enabled'))fail(400,'Missing enabled');if(next.enabled&&!reader().supported)fail(409,'Unsupported topology');state[key]=next}return reader()});
  for(const action of ['enable','disable'])route('/api/blinkA/'+action,'POST',()=>{if(!profile().advancedEapSupported)fail(409,'Unsupported topology');state.blink.enabled=action==='enable';return blink()});
  route('/api/blinkA/delay','POST',p=>{state.blink.delayMs=num(p,'ms',0,30000);return blink()});
  route('/api/blinkA/timing','POST',p=>{patch(state.blink,p,{noaStabilizationSeconds:[1,20],cancelPauseSeconds:[10,100]});return blink()});
  route('/api/blinkA/tx-mode','POST',p=>{state.blink.txMode=num(p,'mode',0,1);return blink()});
  for(const action of ['enable','disable'])route('/api/summon/tlssc-'+action,'POST',()=>{state.summon.tlssc=action==='enable';return summon()});
  for(const [suffix,key] of [['highway-gate','tlsscHighwayGateEnabled'],['noa-block','tlsscBlockInNoa']])route('/api/summon/tlssc-'+suffix,'POST',p=>{state.summon[key]=!!num(p,'enabled',0,1);return summon()});
  route('/api/r79/update','POST',p=>{lab();const next=clone(state.r79);patch(next,p,{mode:[1,2],bit18Mode:[0,1],hw3Enabled:'bool',mode1TxWaitMode:[0,1],mode1DelayMs:[0,340],mode2DelayMs:[0,2000]});for(const [key,target] of [['mode1Reinject','mode1ReinjectEnabled'],['mode2Reinject','mode2ReinjectEnabled']])if(p.has(key))next[target]=!!num(p,key,0,1);if(next.hw3Enabled&&!r79().hw3Supported)fail(409,'HW3 unsupported');state.r79=next;return r79()});
  route('/api/r79/ap-control/update','POST',p=>{lab();const next=clone(state.r79Ap);patch(next,p,{enabled:'bool',mode:[0,1],delaySeconds:[2,10],allowManualDriving:'bool'});if(JSON.stringify(next)!==JSON.stringify(state.r79Ap))apSince=Date.now();state.r79Ap=next;return apControl()});
  route('/api/ulc/update','POST',p=>{lab();const next=clone(state.ulc);for(const [key,target] of [['confirm','stalkConfirmEnabled'],['timing','stalkConfirmTimingMode'],['alcOff','alcMode'],['blind','ulcBlindMode'],['ulcOff','ulcOffHighwayMode']])if(p.has(key)){let v=p.get(key)==='stock'?255:num(p,key,0,key==='blind'?3:1);if(key==='confirm')v=!!v;if(key==='alcOff')v=v?2:0;next[target]=v}state.ulc=next;return ulc()});
  route('/api/lab/auto-lane-change/update','POST',p=>{lab();const next=clone(state.ulc);patch(next,p,{autoLaneChangeEnabled:'bool'});if(p.has('enabled'))next.autoLaneChangeEnabled=!!num(p,'enabled',0,1);if(p.has('bus'))next.autoLaneChangeTargetBus=num(p,'bus',1,3);state.ulc=next;return ulc()});
  const countryUpdate=p=>{const next=clone(state.country);patch(next,p,{countryMode:[0,3],mapMode:[0,2]});if(p.has('mode'))next.countryMode=num(p,'mode',0,3);state.country=next;return country()};
  route('/api/country/update','POST',countryUpdate);route('/api/lab/country/update','POST',countryUpdate);
  const visionUpdate=p=>{lab();const next=clone(state.vision);if(p.has('disabled'))next.requestDisabled=!!num(p,'disabled',0,1);if(p.has('bus')){next.bus=num(p,'bus',0,1);if(next.bus===1&&!vision().bodySupported)fail(409,'BODY bus unsupported')}state.vision=next;return vision()};
  route('/api/vision-control/update','POST',visionUpdate);route('/api/lab/vision-control/update','POST',visionUpdate);
  route('/api/lab/summon-heartbeat/update','POST',p=>{lab();if(!heartbeat().supported)fail(409,'Unsupported topology');const next=clone(state.heartbeat);patch(next,p,{enabled:'bool'});if(p.has('value'))next.selectedValue=num(p,'value',0,3);state.heartbeat=next;return heartbeat()});
  route('/api/lab/driver-window/open','POST',()=>{lab();if(!driverWindow().available){state.driverWindow.blocked++;fail(409,'DEMO requires PARK and supported profile')}state.driverWindow.requests++;state.driverWindow.completed++;state.driverWindow.txOk+=2;state.driverWindow.lastResult='COMPLETED';return driverWindow()});
  route('/api/pedalmap/set','POST',p=>{if(!profile().pedalMapSupported)fail(409,'PedalMap unsupported');const raw=({stock:255,chill:0,comfort:0,sport:1,performance:2,'0':0,'1':1,'2':2})[(p.get('mode')||'').toLowerCase()];if(raw===undefined)fail(400,'Invalid mode');if(!online()||state.scenario==='parked')fail(409,'DEMO live state blocks PedalMap');state.pedal.targetRaw=raw;state.pedal.txOk++;state.pedal.immediateTxOk++;return pedal()});
  for(const [suffix,key] of [['lab','lab'],['s3xy','s3xy'],['door-cancel','doorCancel'],['banned','banned'],['tlssc-restore','tlsscRestore'],['ap-drive-profile','apDriveProfile']])route('/api/features/'+suffix,'POST',p=>{const next=clone(state.features),f=features();if(p.has('enabled')){const v=!!num(p,'enabled',0,1);const capability={banned:'bannedSupported',tlsscRestore:'tlsscRestoreSupported',apDriveProfile:'apDriveProfileSupported'}[key];if(v&&capability&&!f[capability])fail(409,'Unsupported feature');next[key]=v}if(key==='apDriveProfile'&&p.has('regen')){const v=num(p,'regen',1,20);if(![1,10,20].includes(v))fail(400,'Invalid regen');next.apDriveProfileRegenRaw=v}state.features=next;return features()});
  route('/api/researchcapture/labels','POST',p=>{lab();const slot=p.get('slot'),label=p.get('label');if(!['A','B','C','D'].includes(slot)||!label||label.length>80)fail(400,'Invalid slot or label');state.research.labels[slot]=label;return capture()});
  route('/api/researchcapture/config','POST',p=>{lab();const next=clone(state.research);next.preWindowMs=num(p,'preMs',2000,15000);next.postWindowMs=num(p,'postMs',2000,10000);if(![2000,5000,10000,15000].includes(next.preWindowMs)||![2000,5000,10000].includes(next.postWindowMs))fail(400,'Unsupported PRE/POST window');state.research=next;return capture()});
  route('/api/researchcapture/mode','POST',p=>{lab();const modes={SNAPSHOT:'SNAPSHOT','0':'SNAPSHOT',RAW:'RAW_TRANSITION','1':'RAW_TRANSITION',RAW_TRANSITION:'RAW_TRANSITION'},raw=(p.get('mode')||'').toUpperCase();if(state.allFeatures&&['RAW_AUTO_ALC','ULC_CONFIRM'].includes(raw))modes[raw]=raw;if(!modes[raw])fail(400,'Unsupported capture mode');state.research.captureMode=modes[raw];return capture()});
  route('/api/researchcapture/start','POST',p=>{lab();const c=state.research,slot=p.get('slot');if(!['A','B','C','D'].includes(slot))fail(400,'Invalid slot');if(c.completedSegments>=8)fail(409,'Capture full');if(!online())fail(409,'DEMO CAN offline');c.requests++;c.completedSegments++;c.samples+=42;c.lastSlot=slot;c.lastLabel=c.labels[slot];c.history.push({slot,label:c.lastLabel,samples:42});return capture()});
  route('/api/researchcapture/reset','POST',()=>{lab();const c=defaults().research;c.labels=state.research.labels;c.captureMode=state.research.captureMode;state.research=c;return capture()});
  route('/api/drivermonitor/start','POST',p=>{lab();const c=state.monitor,slot=p.get('slot');if(!['A','B','C','D','E','F'].includes(slot))fail(400,'Invalid slot');if(c.segments>=12||!online())fail(409,'Capture blocked');c.requests++;c.segments++;c.samples+=64;c.history.push({slot,samples:64});return monitor()});
  route('/api/drivermonitor/reset','POST',()=>{lab();state.monitor=defaults().monitor;return monitor()});
  function requireBle(){if(!state.s3xy.bluetoothEnabled||!state.features.s3xy)fail(409,'DEMO Bluetooth disabled')}
  for(const action of ['enable','disable']){route('/api/s3xy/bluetooth-'+action,'POST',()=>{state.s3xy.bluetoothEnabled=action==='enable';for(const d of state.s3xy.devices){d.connected=action==='enable'&&d.autoConnect&&!d.paused;d.state=d.connected?'READY':'OFFLINE'}return s3xy()});route('/api/s3xy/auto-'+action,'POST',()=>{state.s3xy.autoEnabled=action==='enable';return s3xy()})}
  route('/api/s3xy/scan','POST',()=>{requireBle();const c=state.s3xy;c.scanResults=[{name:'DEMO New Button',address:'DE:00:00:00:00:03',rssi:-52,compatible:true,paired:c.devices.some(d=>d.address==='DE:00:00:00:00:03')}];c.scanState='DONE';return s3xy()});
  route('/api/s3xy/pair','POST',p=>{requireBle();const c=state.s3xy,address=p.get('address');if(!/^(?:[\da-f]{2}:){5}[\da-f]{2}$/i.test(address||''))fail(400,'Invalid address');if(c.devices.some(d=>d.address.toLowerCase()===address.toLowerCase()))fail(409,'Already paired');if(c.devices.length>=3)fail(409,'Registry full');const id=[1,2,3].find(n=>!c.devices.some(d=>d.id===n));c.devices.push(device(id,'DEMO New Button',address));c.scanResults=c.scanResults.map(d=>({...d,paired:d.address===address}));return s3xy()});
  const actions=['none','noa_cancel','left_blinker','right_blinker','accel_mode_toggle','performance_mode','tlssc_toggle','auto_blinker_toggle','research_capture_a','research_capture_b','research_capture_c','research_capture_d','research_capture_reset'];
  for(const suffix of ['connect','disconnect','forget','handshake','rename','action','auto'])route('/api/s3xy/device/'+suffix,'POST',p=>{const d=state.s3xy.devices.find(d=>String(d.id)===p.get('id'));if(!d)fail(404,'Unknown demo device');if(['connect','disconnect','handshake','forget'].includes(suffix))requireBle();if(suffix==='connect'||suffix==='disconnect'){d.connected=suffix==='connect';d.paused=!d.connected;d.state=d.connected?'READY':'OFFLINE'}if(suffix==='forget')state.s3xy.devices=state.s3xy.devices.filter(x=>x!==d);if(suffix==='handshake'){if(!d.connected)fail(409,'Device disconnected');d.handshakeAckCount++;d.lastNotify='DEMO HANDSHAKE ACK'}if(suffix==='rename'){const name=(p.get('name')||'').trim();if(!name||name.length>48)fail(400,'Invalid name');d.name=name}if(suffix==='auto')d.autoConnect=!!num(p,'enabled',0,1);if(suffix==='action'){const gesture=p.get('gesture'),action=p.get('action');if(!['single','double','long'].includes(gesture)||!actions.includes(action))fail(400,'Invalid mapping');if(['performance_mode','accel_mode_toggle'].includes(action)&&!profile().pedalMapSupported||action==='auto_blinker_toggle'&&!profile().advancedEapSupported||['left_blinker','right_blinker'].includes(action)&&!profile().turnSignalSupported)fail(409,'Action unsupported for topology');d[gesture+'Action']=action}return s3xy()});
  route('/api/s3xy/clear','POST',()=>{for(const d of state.s3xy.devices){d.notifyCount=0;d.singleCount=0;d.doubleCount=0;d.longCount=0}return s3xy()});
  function reboot(){state.reboots++;state.started=Date.now();apSince=Date.now();state.pedal.targetRaw=255;state.heartbeat.enabled=false;state.research.samples=0;state.research.completedSegments=0;state.research.history=[];state.monitor=defaults().monitor;state.s3xy.scanResults=[];return {ok:true,demo:true,rebooting:true,message:'Demo restart · no controller is accessed',status:202};}
  route('/api/s3xy/reset-all','POST',()=>{state.s3xy.devices=[];return reboot()});
  route('/api/system/reboot','POST',reboot);
  route('/api/system/reset-stats','POST',()=>{state.system=defaults().system;state.system.mcpTxOk=0;state.r79.txOk=0;state.r79.txFail=0;state.blink.txOk=0;state.blink.txRequests=0;return system()});
  route('/api/system/reinit-can','POST',()=>{state.system.canHardReinit++;state.system.canLastHardReason='DEMO USER';state.system.canLastHardDiagReasonName='DEMO REINIT';return system()});
  route('/api/system/reset-settings','POST',()=>{const fresh=defaults();for(const k of ['features','nag','human','driverMonitoring','isa','blink','summon','r79','r79Ap','ulc','country','vision','heartbeat','driverWindow','pedal','research','monitor','system'])state[k]=fresh[k];return reboot()});
  for(const path of ['/api/system/factory-reset','/api/system/reset-nvs-keep-ble'])route(path,'POST',()=>{const ble=clone(state.s3xy),scenario=state.scenario,allFeatures=state.allFeatures;reset();state.setupMode=true;state.scenario=scenario;state.allFeatures=allFeatures;state.wifi={ssid:'T2CAN',ip:'192.168.4.1',passwordIsDefault:true};state.s3xy=path.endsWith('keep-ble')?ble:{...state.s3xy,devices:[]};return reboot()});
  route('/api/profile/select','POST',p=>{const model=num(p,'profile',1,5),topology=model===1?1:num(p,'topology',2,3),turn=topology===3?0:model===1?1:num(p,'turn',1,2);state.model=model;state.topology=topology;state.turn=turn;state.setupMode=false;state.nag.method=profile().nagTorqueSupported?0:1;return {...reboot(),...profile()}});
  route('/api/wifi/apply','POST',p=>{const ssid=p.get('ssid')||'',password=p.get('password')||'',bytes=s=>new TextEncoder().encode(s).length;if(bytes(ssid)<1||bytes(ssid)>32||password&&(bytes(password)<8||bytes(password)>63))fail(400,'Invalid Wi-Fi settings');state.wifi.ssid=ssid;if(password)state.wifi.passwordIsDefault=false;return {...state.wifi,ok:true,demo:true,changed:true,restarting:true,reconnecting:true,message:'Demo Wi-Fi settings · no network is changed'}});
  const csvPaths=['/api/researchcapture/log.csv','/api/drivermonitor/log.csv','/api/s3xy/log.csv','/api/system/boot-capture.csv','/api/system/cana-tx.csv','/api/system/canb-tx.csv'];
  const quote=s=>'"'+String(s).replace(/"/g,'""')+'"';
  for(const path of csvPaths)route(path,'GET',()=>{const research=path.includes('researchcapture'),monitoring=path.includes('drivermonitor'),records=research?state.research.history:monitoring?state.monitor.history:[{slot:'DEMO',label:path,samples:1}],lines=['# DEMO SYNTHETIC DATA - no vehicle capture','timestamp_ms,bus,id,dlc,data,slot,label'];for(const [i,row] of records.entries())lines.push([i*20,'DEMO_CAN_B','0x399',8,quote('00 00 00 00 00 00 00 00'),quote(row.slot),quote(row.label||'DEMO synthetic')].join(','));return {csv:lines.join('\n')+'\n',rows:records.length}});
  route('/update','POST',()=>{state.ota.uploads++;return {ok:true,demo:true,message:'Demo OTA upload complete · no firmware was flashed',bytesWritten:0}});
  window.__t2DemoRoutes=[...routes.keys()];
  async function dispatch(input,init={}){
    const raw=typeof input==='string'?input:input instanceof URL?input.href:input?.url;
    let url;try{url=new URL(raw,location.href)}catch(e){return json({ok:false,demo:true,error:'Invalid URL'},400)}
    const method=String(init.method||input?.method||'GET').toUpperCase();
    window.__t2CopyRequests.push({method,url:url.pathname+url.search});
    const handler=routes.get(url.pathname),base=new URL(location.href);
    if(!handler||url.origin!==base.origin){window.__t2DemoUnhandled.push({method,url:url.href});return json({ok:false,demo:true,error:'Unhandled demo endpoint: '+url.pathname},404)}
    if(!methods.get(url.pathname).split(',').includes(method))return json({ok:false,demo:true,error:'Method not allowed'},405);
    const p=new URLSearchParams(url.search);let body=init.body;
    if(body===undefined&&typeof input?.clone==='function'&&method!=='GET')body=await input.clone().text();
    if(body instanceof URLSearchParams||typeof body==='string'&&!body.trim().startsWith('{'))for(const [k,v] of new URLSearchParams(body))p.set(k,v);
    if(typeof body==='string'&&body.trim().startsWith('{')){try{for(const [k,v] of Object.entries(JSON.parse(body)))p.set(k,String(v))}catch(e){return json({ok:false,demo:true,error:'Invalid JSON'},400)}}
    try{const result=handler(p,method);if(method==='POST')persist();if(result.csv!==undefined){const text=result.csv,size=new TextEncoder().encode(text).length;return new Response(text,{status:200,headers:{'Content-Type':'text/csv','Content-Length':String(size),'X-T2CAN-CSV-Rows':String(result.rows),'Content-Disposition':'attachment; filename="DEMO-synthetic.csv"','X-T2CAN-Demo':'1'}})}return json(result,result.status||200)}catch(e){return json({ok:false,demo:true,error:e.message},e.status||500)}
  }
  function json(value,status=200){return new Response(JSON.stringify({...value,demo:true}),{status,headers:{'Content-Type':'application/json','X-T2CAN-Demo':'1','Cache-Control':'no-store'}})}
  window.fetch=dispatch;
  // The production OTA form uses XMLHttpRequest. This implementation cannot use a real transport.
  class DemoXMLHttpRequest{
    constructor(){this.upload={};this.readyState=0;this.status=0;this.responseText='';this.response='';this.responseType='';this.headers={};this.aborted=false;this.listeners={}}
    open(method,url){this.method=method;this.url=url;this.readyState=1;this.emit('readystatechange')}
    setRequestHeader(key,value){this.headers[key]=value}
    getResponseHeader(key){return this.responseHeaders?.get(key)||null}
    getAllResponseHeaders(){return this.responseHeaders?[...this.responseHeaders].map(([k,v])=>k+': '+v).join('\r\n'):''}
    addEventListener(name,fn){(this.listeners[name]||(this.listeners[name]=[])).push(fn)}
    removeEventListener(name,fn){this.listeners[name]=(this.listeners[name]||[]).filter(x=>x!==fn)}
    emit(name,event={}){event.target=this;if(typeof this['on'+name]==='function')this['on'+name](event);for(const fn of this.listeners[name]||[])fn(event)}
    abort(){this.aborted=true;this.emit('abort');this.emit('loadend')}
    async send(body){this.emit('loadstart');try{for(const loaded of [20,55,100]){await new Promise(r=>setTimeout(r,30));if(this.aborted)return;if(this.upload.onprogress)this.upload.onprogress({lengthComputable:true,loaded,total:100})}const response=await dispatch(this.url,{method:this.method,body,headers:this.headers});if(this.aborted)return;this.status=response.status;this.responseHeaders=response.headers;this.responseText=await response.text();this.response=this.responseType==='json'?JSON.parse(this.responseText):this.responseText;this.readyState=4;this.emit('readystatechange');this.emit('load');this.emit('loadend')}catch(e){this.status=0;this.readyState=4;this.emit('error');this.emit('loadend')}}
  }
  window.XMLHttpRequest=DemoXMLHttpRequest;
})();
