// Detect missing independent 0x3FD opt-in, route/mode coupling, stale-poll
// overwrites, optimistic failed saves and unsupported Body recovery failures.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const {launchBrowser}=require('./browser_test_runtime');const root=path.resolve(__dirname,'..');
async function check(html,label){const browser=await launchBrowser();try{
const page=await browser.newPage({viewport:{width:320,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
let disabled=false,bus=0,profile=1,topology=1,lab=true,ap=true,fresh=true,stock=1,stockFresh=true,reject=false,failRead=false,holdNext=false,release,started;const posts=[];
const stats=()=>{const supported=profile===1?topology===1:[2,3,4,5].includes(profile)&&[2,3].includes(topology),body=supported&&profile!==1&&topology===2,busSupported=supported&&(bus===0||body),gate=disabled&&busSupported&&ap&&fresh&&stock>=0&&stockFresh;return{requestDisabled:disabled,bus,busSelectorVisible:profile!==1,supported,bodySupported:body,busSupported,labEnabled:lab,apActive:ap,apFresh:fresh,stockValid:stock>=0,stockBit:stock,rxAgeMs:stockFresh?50:5000,rxCount:4,gateOpen:gate,txOk:12,txFail:1,state:!busSupported?'UNSUPPORTED':!disabled?'OFF':stock<0||!stockFresh?'WAIT_STOCK':!ap||!fresh?'WAIT_AP':stock===0?'STOCK_ZERO':'READY'};};
await page.route('http://v319.test/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:html});let body={},status=200;
if(u.pathname==='/api/features/status')body={lab};if(u.pathname==='/api/profile/status')body={setupMode:false,profile,topology,turn:1};
if(u.pathname==='/api/vision-control/stats'){body=stats();if(failRead){status=503;body={error:'unavailable'};}if(holdNext){holdNext=false;await new Promise(resolve=>{release=resolve;started();});}}
if(u.pathname==='/api/vision-control/update'){posts.push(u.searchParams.toString());if(reject){status=503;body={error:'save-failed'};}else{if(u.searchParams.has('disabled'))disabled=u.searchParams.get('disabled')==='1';if(u.searchParams.has('bus'))bus=Number(u.searchParams.get('bus'));body=stats();}}
await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});});
const boot=async()=>{await page.waitForFunction(()=>universalBootReady);await page.evaluate(()=>{universalBootReady=false;labEnabled=true;document.body.classList.remove('setup-active');});};
await page.goto('http://v319.test/',{waitUntil:'domcontentloaded'});await boot();
assert.equal(await page.locator('main[data-page="settings"] [data-panel="panelVisionControl"]').count(),1,'Settings must expose Visual Speed Control');
assert.equal(await page.locator('main[data-page="lab"] [data-panel="panelVisionControl"], [data-panel="panelLabVisionControl"]').count(),0,'LAB must not own the production feature');
assert.equal(await page.locator('main[data-page="settings"] [data-panel="panelVisionControl"] .listkey').textContent(),'Visual Speed Control');
const setup=()=>page.evaluate(async()=>{openPanel('panelVisionControl');await fetchVisionControlLab();});await setup();
assert.equal(await page.locator('#panelVisionControl .panelHero').textContent(),'Visual Speed Control');
assert.equal(await page.locator('#visionControlDisableToggle').isChecked(),false);assert.equal(await page.locator('#visionControlState').textContent(),'OFF · STOCK');assert.equal(await page.locator('#visionControlBusWrap').isVisible(),false,'YL has fixed VH');
const save=(key,value)=>page.evaluate(async({key,value})=>{const el=$(key==='bus'?'visionControlBus':'visionControlDisableToggle');if(key==='bus')el.value=String(value);else el.checked=value;await el.onchange();},{key,value});
await save('disabled',true);assert.deepEqual(posts,['disabled=1']);assert.equal(await page.locator('#visionControlDisableToggle').isChecked(),true);assert.equal(await page.locator('#visionControlStock').textContent(),'1 → 0');assert.equal(await page.locator('#visionSpeedDisableToggle, #adaptiveSpeedDisableToggle').count(),0,'retired 0x3F8 controls stay removed');
profile=3;topology=2;await page.evaluate(()=>fetchVisionControlLab());await save('bus',1);assert.equal(await page.locator('#visionControlDisableToggle').isChecked(),true,'bus preserves opt-in');await save('disabled',false);assert.equal(await page.locator('#visionControlBus').inputValue(),'1','opt-in preserves bus');await save('disabled',true);
await page.reload({waitUntil:'domcontentloaded'});await boot();await page.evaluate(()=>showPage('settings'));assert.equal(await page.locator('#visionControlRowState').textContent(),'ON','saved production state must render before opening the panel');await setup();assert.equal(await page.locator('#visionControlDisableToggle').isChecked(),true,'saved selection loads after reload');assert.equal(await page.locator('#visionControlBus').inputValue(),'1');
reject=true;await save('disabled',false);assert.equal(await page.locator('#visionControlDisableToggle').isChecked(),true);await save('bus',0);assert.equal(await page.locator('#visionControlBus').inputValue(),'1');failRead=true;await save('disabled',false);assert.equal(await page.locator('#visionControlDisableToggle').isChecked(),true,'failed POST/read restores saved selection');failRead=false;reject=false;
holdNext=true;const ready=new Promise(resolve=>{started=resolve;});await page.evaluate(()=>{window.__lateVisionControl=fetchVisionControlLab();});await ready;await save('bus',0);release();await page.evaluate(()=>window.__lateVisionControl);assert.equal(await page.locator('#visionControlBus').inputValue(),'0','late poll cannot restore obsolete bus');
for(const[p,t]of[[1,1],[2,2],[2,3],[3,2],[3,3],[4,2],[4,3],[5,2],[5,3]]){profile=p;topology=t;bus=0;await page.evaluate(()=>fetchVisionControlLab());assert.equal(await page.locator('#visionControlDisableToggle').isDisabled(),false,`${label} profile ${p}/${t}`);assert.equal(await page.locator('#visionControlBusWrap').isVisible(),p!==1);assert.equal(await page.locator('#visionControlBus option[value="1"]').isDisabled(),p===1||t!==2);}
profile=3;topology=3;bus=1;await page.evaluate(()=>fetchVisionControlLab());assert.equal(await page.locator('#visionControlState').textContent(),'UNSUPPORTED');assert.equal(await page.locator('#visionControlDisableToggle').isDisabled(),true);assert.equal(await page.locator('#visionControlBus').isDisabled(),false,'Chassis recovery remains available');await save('bus',0);assert.equal(await page.locator('#visionControlState').textContent(),'READY · AP ACTIVE');
lab=false;await page.evaluate(()=>{labEnabled=false;return fetchVisionControlLab();});assert.equal(await page.locator('#visionControlDisableToggle').isDisabled(),false);assert.equal(await page.locator('#visionControlState').textContent(),'READY · AP ACTIVE');lab=true;await page.evaluate(()=>{labEnabled=true;return fetchVisionControlLab();});
ap=false;await page.evaluate(()=>fetchVisionControlLab());assert.equal(await page.locator('#visionControlState').textContent(),'Waiting for AP');assert.equal(await page.locator('#visionControlStock').textContent(),'1 → 1');ap=true;fresh=false;await page.evaluate(()=>fetchVisionControlLab());assert.equal(await page.locator('#visionControlState').textContent(),'Waiting for AP');fresh=true;stockFresh=false;await page.evaluate(()=>fetchVisionControlLab());assert.equal(await page.locator('#visionControlState').textContent(),'Waiting for stock');stockFresh=true;stock=-1;await page.evaluate(()=>fetchVisionControlLab());assert.equal(await page.locator('#visionControlStock').textContent(),'— → —');stock=0;await page.evaluate(()=>fetchVisionControlLab());assert.equal(await page.locator('#visionControlState').textContent(),'Stock already 0 · no TX');assert.equal(await page.locator('#visionControlStock').textContent(),'0 → 0');stock=1;await page.evaluate(()=>fetchVisionControlLab());await page.evaluate(()=>{document.querySelector('#selectSheet')?.classList.remove('show');document.querySelector('#selectSheetBack')?.classList.remove('show');document.activeElement?.blur();});
for(const width of[320,390,430])for(const theme of['light','dark']){await page.setViewportSize({width,height:844});await page.evaluate(t=>{window.t2Theme.setMode(t);openPanel('panelVisionControl');},theme);await page.waitForTimeout(240);assert.equal(await page.locator('#panelVisionControl').isVisible(),true);assert.equal(await page.locator('#panelVisionControl').evaluate(e=>e.scrollWidth<=innerWidth),true,`${label} ${width}/${theme} overflow`);for(const selector of['#visionControlBus','#visionControlDisableToggle'])assert.equal(await page.locator(selector).evaluate(e=>{const r=(e.closest('.toggle')||e).getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;}),true);const dir=process.env.DASHBOARD_SCREENSHOT_DIR;if(dir){fs.mkdirSync(dir,{recursive:true});await page.screenshot({path:path.join(dir,`${label}-visual-speed-control-${width}-${theme}.png`),fullPage:false,animations:'disabled'});}await page.locator('#panelVisionControl').evaluate(e=>{e.scrollTop=e.scrollHeight;});assert.equal(await page.locator('#visionControlSaveState').evaluate(e=>e.getBoundingClientRect().bottom<document.querySelector('#bottomNav').getBoundingClientRect().top),true,'saved status remains reachable above fixed navigation');if(dir)await page.screenshot({path:path.join(dir,`${label}-visual-speed-control-${width}-${theme}-bottom.png`),fullPage:false,animations:'disabled'});await page.locator('#panelVisionControl').evaluate(e=>{e.scrollTop=0;});}
assert.deepEqual(errors,[]);
}finally{await browser.close();}}
(async()=>{await check(fs.readFileSync(path.join(root,'dashboard_source.html'),'utf8'),'source');if(!process.env.V319_DASHBOARD_SOURCE_ONLY){const h=fs.readFileSync(path.join(root,'index_html.h'),'utf8').match(/INDEX_HTML_GZ\[\][^{]*\{([\s\S]*?)\};/)[1];await check(zlib.gunzipSync(Buffer.from(h.match(/0x[\da-f]+/gi).map(x=>parseInt(x,16)))).toString(),'embedded');}})().then(()=>console.log('PASS production Visual Speed Control persistence, profiles, rollback, late polls and responsive source/embedded themes'),e=>{console.error(e);process.exitCode=1;});
