const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const {launchBrowser}=require('./browser_test_runtime');const root=path.resolve(__dirname,'..');

async function check(html,label){const browser=await launchBrowser();try{
  const page=await browser.newPage({viewport:{width:320,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  let enabled=false,value=2,reject=false,holdNext=false,release,started;const posts=[];
  const stats=()=>({ok:true,supported:true,labEnabled:true,enabled,selectedValue:value,gateOpen:true,stockValid:true,stockFresh:true,stockValue:2,stockAgeMs:40,lastAppliedValid:enabled,lastAppliedValue:enabled?value:-1,lastAppliedAgeMs:enabled?20:999999,appliedCount:enabled?12:0,txFail:1,blocked:2,state:enabled?'ACTIVE':'OFF'});
  await page.route('http://v325.test/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:html});let body={},status=200;
    if(u.pathname==='/api/features/status')body={lab:true};else if(u.pathname==='/api/profile/status')body={setupMode:false,profile:1,topology:1,turn:0};else if(u.pathname==='/api/lab/summon-heartbeat/stats'){body=stats();if(holdNext){holdNext=false;await new Promise(resolve=>{release=resolve;started();});}}
    else if(u.pathname==='/api/lab/summon-heartbeat/update'){posts.push(u.searchParams.toString());if(reject){status=503;body={error:'apply-failed'};}else{enabled=u.searchParams.get('enabled')==='1';value=Number(u.searchParams.get('value'));body=stats();}}
    await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
  });
  await page.goto('http://v325.test/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>universalBootReady);await page.evaluate(()=>{universalBootReady=false;labEnabled=true;document.body.classList.remove('setup-active');});
  assert.equal(await page.locator('main[data-page="lab"] [data-panel="panelLabSummonHeartbeat"]').count(),1);
  assert.deepEqual(await page.locator('#summonHeartbeatOverrideValue option').evaluateAll(nodes=>nodes.map(n=>n.value)),['0','1','2','3']);
  await page.evaluate(async()=>{openPanel('panelLabSummonHeartbeat');await fetchSummonHeartbeatOverride();});
  assert.equal(await page.locator('#summonHeartbeatOverrideToggle').isChecked(),false);assert.equal(await page.locator('#summonHeartbeatOverrideValue').inputValue(),'2');assert.equal(await page.locator('#summonHeartbeatStock').textContent(),'2 / 40 ms');
  await page.evaluate(async()=>{$('summonHeartbeatOverrideValue').value='0';await $('summonHeartbeatOverrideValue').onchange();});
  assert.equal(posts.at(-1),'enabled=0&value=0');assert.equal(await page.locator('#summonHeartbeatOverrideValue').inputValue(),'0');
  await page.evaluate(async()=>{$('summonHeartbeatOverrideToggle').checked=true;await $('summonHeartbeatOverrideToggle').onchange();});
  assert.equal(posts.at(-1),'enabled=1&value=0');assert.equal(await page.locator('#summonHeartbeatRuntimeState').textContent(),'ACTIVE');assert.equal(await page.locator('#summonHeartbeatApplied').textContent(),'0 / 0');
  reject=true;await page.evaluate(async()=>{$('summonHeartbeatOverrideValue').value='3';await $('summonHeartbeatOverrideValue').onchange();});assert.equal(await page.locator('#summonHeartbeatOverrideValue').inputValue(),'0','failed POST restores controller state');reject=false;
  holdNext=true;const ready=new Promise(resolve=>{started=resolve;});await page.evaluate(()=>{window.__lateHeartbeat=fetchSummonHeartbeatOverride();});await ready;await page.evaluate(async()=>{$('summonHeartbeatOverrideValue').value='1';await $('summonHeartbeatOverrideValue').onchange();});release();await page.evaluate(()=>window.__lateHeartbeat);assert.equal(await page.locator('#summonHeartbeatOverrideValue').inputValue(),'1','late poll cannot restore obsolete value');
  enabled=false;value=2;await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>universalBootReady);await page.evaluate(()=>{universalBootReady=false;labEnabled=true;document.body.classList.remove('setup-active');});await page.evaluate(async()=>{openPanel('panelLabSummonHeartbeat');await fetchSummonHeartbeatOverride();});assert.equal(await page.locator('#summonHeartbeatOverrideToggle').isChecked(),false,'reboot starts OFF');assert.equal(await page.locator('#summonHeartbeatOverrideValue').inputValue(),'2');
  for(const width of[320,390,430])for(const theme of['light','dark']){await page.setViewportSize({width,height:844});await page.evaluate(t=>{window.t2Theme.setMode(t);openPanel('panelLabSummonHeartbeat');},theme);await page.waitForTimeout(240);assert.equal(await page.locator('#panelLabSummonHeartbeat').evaluate(e=>e.scrollWidth<=innerWidth),true,`${label} ${width}/${theme} overflow`);for(const selector of['#summonHeartbeatOverrideToggle','#summonHeartbeatOverrideValue'])assert.equal(await page.locator(selector).evaluate(e=>{const r=(e.closest('.toggle')||e).getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;}),true);await page.locator('#panelLabSummonHeartbeat').evaluate(e=>{e.scrollTop=e.scrollHeight;});assert.equal(await page.locator('#summonHeartbeatSaveState').evaluate(e=>e.getBoundingClientRect().bottom<document.querySelector('#bottomNav').getBoundingClientRect().top),true);await page.locator('#panelLabSummonHeartbeat').evaluate(e=>{e.scrollTop=0;});}
  assert.deepEqual(errors,[]);
}finally{await browser.close();}}

(async()=>{await check(fs.readFileSync(path.join(root,'dashboard_source.html'),'utf8'),'source');if(!process.env.V325_DASHBOARD_SOURCE_ONLY){const h=fs.readFileSync(path.join(root,'index_html.h'),'utf8').match(/INDEX_HTML_GZ\[\][^{]*\{([\s\S]*?)\};/)[1];await check(zlib.gunzipSync(Buffer.from(h.match(/0x[\da-f]+/gi).map(x=>parseInt(x,16)))).toString(),'embedded');}})().then(()=>console.log('PASS Summon Heartbeat LAB session UI, rollback, stale poll and responsive themes'),e=>{console.error(e);process.exitCode=1;});
