#!/usr/bin/env python3
"""Embed the approved, pre-sized TU icon without a runtime filesystem."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    payload = (ROOT / "assets" / "apple-touch-icon.png").read_bytes()
    rows = ["  " + ", ".join(f"0x{v:02X}" for v in payload[i:i + 16]) + ","
            for i in range(0, len(payload), 16)]
    header = (
        "#pragma once\n#include <Arduino.h>\n\n"
        "// Generated by tools/build_dashboard_icon.py.\n"
        "static const uint8_t APPLE_TOUCH_ICON[] PROGMEM = {\n"
        + "\n".join(rows)
        + f"\n}};\nstatic const size_t APPLE_TOUCH_ICON_LEN = {len(payload)};\n"
    )
    (ROOT / "dashboard_icon.h").write_text(header, encoding="utf-8")
    print(f"Apple touch icon: {len(payload)} bytes")


if __name__ == "__main__":
    main()
