#!/usr/bin/env python3
"""Embed the supplied LAB reference's Latin Geist faces for offline use."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FONTS = (
    ("LAB_GEIST_FONT", ROOT / "fonts" / "geist-latin.woff2"),
    ("LAB_GEIST_MONO_FONT", ROOT / "fonts" / "geist-mono-latin.woff2"),
)


def array(name: str, data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("  " + ", ".join(f"0x{byte:02X}" for byte in data[offset : offset + 16]) + ",")
    return (
        f"static const uint8_t {name}[] PROGMEM = {{\n"
        + "\n".join(rows)
        + f"\n}};\nstatic const size_t {name}_LEN = {len(data)};\n"
    )


out = ["#pragma once", "#include <Arduino.h>", "", "// Generated by tools/build_lab_fonts.py from the supplied LAB reference."]
for name, path in FONTS:
    out.append(array(name, path.read_bytes()))
(ROOT / "lab_fonts.h").write_text("\n".join(out), encoding="utf-8")
print("LAB fonts", *(f"{path.name}={path.stat().st_size}" for _, path in FONTS))
